<?php

/**
 * Implements hook_tribune_post_alter().
 */
function tribune_totoz_tribune_post_alter($node, &$post) {
  drupal_add_css(drupal_get_path('module', 'tribune_totoz') . '/tribune_totoz.css');

  $server = variable_get('tribune_totoz_server_' . $node->nid, 'NULL');

  if ($server and $server != 'NULL') {
    $post['text'] = preg_replace_callback("/(\[:((\w| |_|-)+)\])/",
      function(&$matches) use($server) {
        $totoz_text = $matches[1];
        $totoz_name = $matches[2];
        $text = $totoz_text . '<img src="'. $server . '/' . $totoz_name . '.gif" alt="' . $totoz_name . '" />';
        return l($text, $server . '/' . $totoz_name . '.gif', array('html' => TRUE, 'attributes' => array('class' => array('tribune-totoz'))));
      },
      $post['text']
    );
  }
}

/**
 * Implements hook_tribune_form().
 */
function tribune_totoz_tribune_form($node, $form_state) {
  $default_value = 'NULL';
  if (!empty($node->nid)) {
    $default_value = variable_get('tribune_totoz_server_' . $node->nid, 'NULL');
  }

  return array(
    'tribune_totoz_details' => array(
      '#weight' => 10,
      '#type' => 'fieldset',
      '#title' => t('Totoz server'),

      'tribune_totoz_server' => array(
        '#type' => 'select',
        '#title' => t('Server'),
        '#description' => t('Where to get the images from.'),
        '#default_value' => $default_value,
        '#options' => array(
          'NULL' => t('Disabled'),
          'https://sfw.totoz.eu' => t('Totoz.eu (safe for work)'),
          'https://totoz.eu' => t('Totoz.eu'),
          'http://forum.hardware.fr/images/perso' => t('Hardware.fr (moderated)'),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_node_update().
 */
function tribune_totoz_node_update($node) {
  if ($node->type == 'tribune' and isset($node->tribune_totoz_server)) {
    variable_set('tribune_totoz_server_' . $node->nid, $node->tribune_totoz_server);
  }
}

/**
 * Implements hook_node_insert().
 */
function tribune_totoz_node_insert($node) {
  if ($node->type == 'tribune' and isset($node->tribune_totoz_server)) {
    variable_set('tribune_totoz_server_' . $node->nid, $node->tribune_totoz_server);
  }
}

/**
 * Implements hook_node_delete().
 */
function tribune_totoz_node_delete($node) {
  if ($node->type == 'tribune') {
    variable_del('tribune_totoz_server_' . $node->nid);
  }
}
