<?php

/**
 * Implements hook_block_info().
 */
function tribune_block_block_info() {
  $tribunes = node_load_multiple(array(), array('type' => 'tribune'));

  $blocks = array();

  foreach ($tribunes as $tribune) {
    $blocks['tribune-' . $tribune->nid] = array(
      'info' => t('Tribune: !title [nid: !nid]', array('!title' => $tribune->title, '!nid' => $tribune->nid)),
      'cache' => DRUPAL_CACHE_PER_USER,
      'properties' => array(
        'nid' => $tribune->nid,
      ),
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_info().
 */
function tribune_block_block_configure($delta = '') {
  $nid = str_replace('tribune-', '', $delta);
  if ($node = node_load($nid)) {
    return array(
      'tribune_block_display_posts_' . $node->nid => array(
        '#type' => 'textfield',
        '#title' => t('Number of posts to display'),
        '#default_value' => variable_get('tribune_block_display_posts_' . $node->nid, 10),
      ),
    );
  }
}

/**
 * Implements hook_block_save().
 */
function tribune_block_block_save($delta = '', $edit = array()) {
  $nid = str_replace('tribune-', '', $delta);
  if ($node = node_load($nid)) {
    variable_set('tribune_block_display_posts_' . $node->nid, $edit['tribune_block_display_posts_' . $node->nid]);
  }
}

/**
 * Implements hook_block_view().
 */
function tribune_block_block_view($delta = '') {
  $nid = str_replace('tribune-', '', $delta);
  if ($node = node_load($nid)) {
    drupal_add_css(drupal_get_path('module', 'tribune_block') . '/tribune_block.css');
    $node->tribune_display_posts = variable_get('tribune_block_display_posts_' . $node->nid, 10);
    return array(
      'subject' => l($node->title, 'node/' . $node->nid),
      'content' => '<div class="tribune-block">' . drupal_render(tribune_view($node)->content) . '</div>',
    );
  }
}

/**
 * Implements hook_node_delete().
 */
function tribune_block_node_delete($node) {
  if ($node->type == 'tribune') {
    variable_del('tribune_block_display_posts_' . $node->nid);
  }
}
